### ISSUE TITLE
The public version doesn't support  ELF format binary 

### ISSUE THREAD

**Issue by Hyberlion** [angr/patcherex#11]
according to the paper,the ramblr is have a good effect on elf binary reassembling , but my experiment and other issues has shown that the public version doesn't support ELF format binary well. Would you mind releasing some test elf binary that public version Ramblr supported. Thanks!

**Comment by ltfish** [comment]
> but my experiment and other issues has shown that the public version doesn't support ELF format binary well

Can you please detail your experiment and provide binaries you used to test Ramblr? We can debug it to see what the issue might be.

As for the ELF binaries we used, they are generated from compiling coreutils with GCC 4.8 from Ubuntu 16.04 (as far as I remember).
