### ISSUE TITLE
Refactoring utils.py to work with x64

### ISSUE THREAD

**Issue by jkrshnmenon** [angr/patcherex#17]
Currently, the utils.py uses constants that work only with x86 32 bit.
It would be good to re-implement the functionalities in this file as a class which contains some information about the angr.Project instance.

I can try to do this. But if anyone has a better idea I can try to help with it.

**Comment by ltfish** [comment]
Please wait until we migrate to Python 3. (At the same time, feel free to work on the py3k branch.)
