### ISSUE TITLE
x64 arithmetic immediates get truncated

### ISSUE THREAD

**Issue by symike** [angr/patcherex#2]
When lifting code from a simply x64 ELF binary with angr and printing out the capstone instructions, there is an instruction such as this:

```
0x400439:  and  rsp, 0xfffffffffffffff0
```

However, when patcherex tries to generate a new binary using the Reassembler backend (0 patches applied - i.e. try to just generate a new binary from the old one with no modifications), similar to the tutorial in the patcherex README, I get the following error:

  File "angr/patcherex/patcherex/backends/reassembler_backend.py", line 134, in save
    raise CompilationError("File: %s Error: %s" % (tmp_file_path,res))
patcherex.errors.CompilationError: File: /tmp/print0nP4oL.s Error: ('', '/tmp/print0nP4oL.s:46:7: error: invalid operand for instruction\n        andq    $0xfffffff0, %rsp\n 

When I look in the temp-generated assembly file /tmp/print0nP4oL.s:, I notice the following at the referenced line 46:

```
# 0x400439: andq  $0xfffffff0, %rsp [IMM, REG]
andq  $0xfffffff0, %rsp
```

The value seems to have changed, and specifically the sign extension seems to be gone. In any case, there is no binary generated. The code is an extremely simple C program compiled with gcc (with no flags passed to it) on 64-bit Linux:

```
#include <stdio.h>

int main(int argc, char **argv) {
  int x, y, z;
  x = 1234567890;
  printf("%d\n", x);
  y = 1111111101;
  z = x - y; // z = 123456789
  printf("%d\n", z);
  return 0;
}
```

I've also tried changing the assemble.sh script called by compilerex to use other assemblers instead of clang (such as gcc and gas), but have the same problem.

I can provide the binary or more information if needed.

This may actually be an issue in compilerex or another module, but I'm not entirely sure.

**Comment by ltfish** [comment]
That's an issue in reassembler.py and has been addressed in our internal patches. Please wait for updates :-)

**Comment by fabriziobiondi** [comment]
Any updates on this?

**Comment by ltfish** [comment]
Yes! Wait for a new release :-)

**Comment by AndrewFasano** [comment]
I'm also running into this bug. Any idea when the new release will come out?

**Comment by Hyberlion** [comment]
I'm also running into this bug. Any idea when the new release will come out?
