### ISSUE TITLE
Reassembler Issues

### ISSUE THREAD

**Issue by m1ghtym0** [angr/patcherex#22]
Please check the `feat/ezpz` branch.
The remaining tests failing are:
- [ ] adversarial
- [ ] nxstack
- [ ] backdoor
- [ ] bitflip
- [ ] indirectcfi
- [ ] shiftstack
- [ ] transmitprotection

All of them are Reassembler issues.
The CI is also broken though.
@ltfish I'm not sure where those issue would originate from?
The Reassembler backend wasn't really touched and the clang version is shipped...

**Comment by twizmwazin** [comment]
This repo isn't in CI at the moment, Travis has been decommissioned for the better part of a year now. I can look at getting it into Azure CI in the near future.
